<?php

namespace Database\Seeders;

use App\Models\FattyAcid;
use Illuminate\Database\Seeder;

class FattyAcidSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach ($this->catalog() as $definition) {
            FattyAcid::query()->updateOrCreate(
                ['key' => $definition['key']],
                $definition,
            );
        }
    }

    /**
     * @return array<int, array<string, int|float|string|bool|null>>
     */
    private function catalog(): array
    {
        return [
            [
                'key' => 'caprylic',
                'name' => 'Caprylic',
                'short_name' => 'C8:0',
                'chain_length' => 8,
                'double_bonds' => 0,
                'saturation_class' => 'saturated',
                'iodine_factor' => 0,
                'default_group_key' => 'vs',
                'display_order' => 10,
                'is_core' => false,
                'is_active' => true,
                'default_hidden_below_percent' => 0.5,
                'source_data' => null,
            ],
            [
                'key' => 'capric',
                'name' => 'Capric',
                'short_name' => 'C10:0',
                'chain_length' => 10,
                'double_bonds' => 0,
                'saturation_class' => 'saturated',
                'iodine_factor' => 0,
                'default_group_key' => 'vs',
                'display_order' => 20,
                'is_core' => false,
                'is_active' => true,
                'default_hidden_below_percent' => 0.5,
                'source_data' => null,
            ],
            [
                'key' => 'lauric',
                'name' => 'Lauric',
                'short_name' => 'C12:0',
                'chain_length' => 12,
                'double_bonds' => 0,
                'saturation_class' => 'saturated',
                'iodine_factor' => 0,
                'default_group_key' => 'vs',
                'display_order' => 30,
                'is_core' => true,
                'is_active' => true,
                'default_hidden_below_percent' => 0.5,
                'source_data' => null,
            ],
            [
                'key' => 'myristic',
                'name' => 'Myristic',
                'short_name' => 'C14:0',
                'chain_length' => 14,
                'double_bonds' => 0,
                'saturation_class' => 'saturated',
                'iodine_factor' => 0,
                'default_group_key' => 'vs',
                'display_order' => 40,
                'is_core' => true,
                'is_active' => true,
                'default_hidden_below_percent' => 0.5,
                'source_data' => null,
            ],
            [
                'key' => 'palmitic',
                'name' => 'Palmitic',
                'short_name' => 'C16:0',
                'chain_length' => 16,
                'double_bonds' => 0,
                'saturation_class' => 'saturated',
                'iodine_factor' => 0,
                'default_group_key' => 'hs',
                'display_order' => 50,
                'is_core' => true,
                'is_active' => true,
                'default_hidden_below_percent' => 0.5,
                'source_data' => null,
            ],
            [
                'key' => 'palmitoleic',
                'name' => 'Palmitoleic',
                'short_name' => 'C16:1',
                'chain_length' => 16,
                'double_bonds' => 1,
                'saturation_class' => 'monounsaturated',
                'iodine_factor' => 0.995,
                'default_group_key' => 'mu',
                'display_order' => 60,
                'is_core' => false,
                'is_active' => true,
                'default_hidden_below_percent' => 0.5,
                'source_data' => null,
            ],
            [
                'key' => 'stearic',
                'name' => 'Stearic',
                'short_name' => 'C18:0',
                'chain_length' => 18,
                'double_bonds' => 0,
                'saturation_class' => 'saturated',
                'iodine_factor' => 0,
                'default_group_key' => 'hs',
                'display_order' => 70,
                'is_core' => true,
                'is_active' => true,
                'default_hidden_below_percent' => 0.5,
                'source_data' => null,
            ],
            [
                'key' => 'ricinoleic',
                'name' => 'Ricinoleic',
                'short_name' => 'C18:1-OH',
                'chain_length' => 18,
                'double_bonds' => 1,
                'saturation_class' => 'hydroxy_unsaturated',
                'iodine_factor' => 0.901,
                'default_group_key' => 'sp',
                'display_order' => 80,
                'is_core' => true,
                'is_active' => true,
                'default_hidden_below_percent' => 0.5,
                'source_data' => null,
            ],
            [
                'key' => 'oleic',
                'name' => 'Oleic',
                'short_name' => 'C18:1',
                'chain_length' => 18,
                'double_bonds' => 1,
                'saturation_class' => 'monounsaturated',
                'iodine_factor' => 0.860,
                'default_group_key' => 'mu',
                'display_order' => 90,
                'is_core' => true,
                'is_active' => true,
                'default_hidden_below_percent' => 0.5,
                'source_data' => null,
            ],
            [
                'key' => 'linoleic',
                'name' => 'Linoleic',
                'short_name' => 'C18:2',
                'chain_length' => 18,
                'double_bonds' => 2,
                'saturation_class' => 'polyunsaturated',
                'iodine_factor' => 1.732,
                'default_group_key' => 'pu',
                'display_order' => 100,
                'is_core' => true,
                'is_active' => true,
                'default_hidden_below_percent' => 0.5,
                'source_data' => null,
            ],
            [
                'key' => 'linolenic',
                'name' => 'Linolenic',
                'short_name' => 'C18:3',
                'chain_length' => 18,
                'double_bonds' => 3,
                'saturation_class' => 'polyunsaturated',
                'iodine_factor' => 2.616,
                'default_group_key' => 'pu',
                'display_order' => 110,
                'is_core' => true,
                'is_active' => true,
                'default_hidden_below_percent' => 0.5,
                'source_data' => null,
            ],
            [
                'key' => 'arachidic',
                'name' => 'Arachidic',
                'short_name' => 'C20:0',
                'chain_length' => 20,
                'double_bonds' => 0,
                'saturation_class' => 'saturated',
                'iodine_factor' => 0,
                'default_group_key' => 'hs',
                'display_order' => 120,
                'is_core' => false,
                'is_active' => true,
                'default_hidden_below_percent' => 0.5,
                'source_data' => null,
            ],
            [
                'key' => 'gondoic',
                'name' => 'Gondoic',
                'short_name' => 'C20:1',
                'chain_length' => 20,
                'double_bonds' => 1,
                'saturation_class' => 'monounsaturated',
                'iodine_factor' => 0.786,
                'default_group_key' => 'mu',
                'display_order' => 130,
                'is_core' => false,
                'is_active' => true,
                'default_hidden_below_percent' => 0.5,
                'source_data' => null,
            ],
            [
                'key' => 'behenic',
                'name' => 'Behenic',
                'short_name' => 'C22:0',
                'chain_length' => 22,
                'double_bonds' => 0,
                'saturation_class' => 'saturated',
                'iodine_factor' => 0,
                'default_group_key' => 'hs',
                'display_order' => 140,
                'is_core' => false,
                'is_active' => true,
                'default_hidden_below_percent' => 0.5,
                'source_data' => null,
            ],
            [
                'key' => 'erucic',
                'name' => 'Erucic',
                'short_name' => 'C22:1',
                'chain_length' => 22,
                'double_bonds' => 1,
                'saturation_class' => 'monounsaturated',
                'iodine_factor' => 0.723,
                'default_group_key' => 'mu',
                'display_order' => 150,
                'is_core' => false,
                'is_active' => true,
                'default_hidden_below_percent' => 0.5,
                'source_data' => null,
            ],
        ];
    }
}
