<?php

return [
    'categories' => ['all' => 'Tous', 'carrier_oil' => 'Huiles de base', 'essential_oil' => 'Huiles essentielles', 'fragrance_oil' => 'Parfums', 'botanical_extract' => 'Extraits végétaux', 'co2_extract' => 'Extraits CO2', 'liquid' => 'Liquides', 'glycol' => 'Glycols', 'clay' => 'Argiles', 'colorant' => 'Colorants', 'preservative' => 'Conservateurs', 'additive' => 'Ajouts'],
    'accessibility' => ['formula_save_bar' => 'Barre d’enregistrement de la formule', 'zero_quantity_note' => 'Les ingrédients dont la quantité est nulle restent dans la formule.', 'weight_unit' => 'Unité de poids', 'entry_mode' => 'Mode de saisie des quantités', 'product_use' => 'Utilisation du produit', 'filter_category' => 'Filtrer par catégorie', 'ingredient_list' => 'Liste des ingrédients', 'user_owned' => 'Ingrédient créé ou modifié par l’utilisateur', 'show_ingredient_details' => 'Afficher les détails de l’ingrédient', 'ingredient_details' => 'Détails de l’ingrédient', 'add_ingredient' => 'Ajouter l’ingrédient', 'choose_phase' => 'Choisir une phase pour cet ingrédient'],
    'cosmetic' => ['title' => 'Ingrédients de la formule', 'instruction' => 'Organisez les ingrédients par phase, puis saisissez un pourcentage ou un poids.', 'phase' => 'Phase', 'phase_name' => 'Nom de la phase', 'move_up' => 'Monter', 'move_down' => 'Descendre', 'percent_of_formula' => ':percentage % de la formule', 'remove_phase' => 'Supprimer la phase', 'drop_here' => 'Déposez des ingrédients ici', 'formula_total' => 'Total de la formule', 'add_phase' => 'Ajouter une phase', 'formula_balanced' => 'La formule totalise 100 %', 'formula_unbalanced' => 'La formule doit totaliser 100 %', 'balance_label' => 'Total de la formule', 'blend_only' => 'Mélange uniquement', 'category_label' => 'Catégorie', 'entry_label' => 'Quantités', 'exposure_label' => 'Utilisation du produit', 'label_label' => 'Étiquette', 'label_context' => 'Cadre d’étiquetage', 'quantity_complete_singular' => '1 ingrédient a une quantité.', 'quantity_complete_plural' => ':count ingrédients ont une quantité.', 'no_screening_rules' => 'Aucune règle de contrôle pour ce cadre.', 'allergen_singular' => ':count allergène', 'allergen_plural' => ':count allergènes', 'substance_singular' => ':count substance', 'substance_plural' => ':count substances', 'show' => 'Afficher', 'hide' => 'Masquer', 'show_details' => 'Afficher les détails', 'hide_details' => 'Masquer les détails', 'weight_with_unit' => 'Poids (:unit)', 'add_to_phase' => 'Ajouter à :phase', 'drag_ingredient' => 'Faire glisser pour réordonner cet ingrédient', 'show_ingredient_details' => 'Afficher les détails de l’ingrédient', 'remove_ingredient' => 'Supprimer l’ingrédient', 'percentage_for' => 'Pourcentage de :ingredient', 'weight_for' => 'Poids de :ingredient'],
    'headings' => ['soap_qualities' => 'Qualités Soapkraft', 'fatty_acid_profile' => 'Profil des acides gras'],
    'common' => ['ingredient' => 'Ingrédient', 'oil' => 'Huile', 'weight' => 'Poids', 'additives' => 'Ajouts', 'fragrance' => 'Parfums et aromatiques', 'fatty_acids' => 'Acides gras', 'lye_type' => 'Type de soude', 'dual_lye' => 'Soude mixte', 'superfat' => 'Surgraissage', 'rinse_off' => 'Produit rincé', 'leave_on' => 'Produit non rincé', 'product_category' => 'Catégorie de produit', 'choose_later' => 'Choisir plus tard', 'total_batch' => 'Quantité totale du lot', 'cosmetic_categories_unavailable' => 'Les catégories de produit sont actuellement indisponibles.', 'label_compliance' => 'Étiquette et conformité', 'water_percent' => 'Eau en % des huiles', 'water_ratio' => 'Rapport eau : soude', 'lye_concentration' => 'Concentration de soude', 'formula_percent' => '% de la formule'],
    'header' => ['section' => 'Produit', 'product_name' => 'Nom du produit', 'untitled_soap' => 'Savon sans titre', 'untitled_cosmetic' => 'Produit cosmétique sans titre', 'product_sheet' => 'Fiche produit', 'locked' => 'Verrouillé', 'saving' => 'Enregistrement…', 'save' => 'Enregistrer', 'lock_product' => 'Verrouiller le produit', 'unlock_product' => 'Déverrouiller le produit', 'more_actions' => 'Autres actions', 'product_details' => 'Détails du produit', 'duplicate_product' => 'Dupliquer le produit', 'new_product' => 'Nouveau produit', 'current_product' => 'Produit actuel', 'new_soap' => 'Nouveau savon', 'new_cosmetic' => 'Nouveau produit cosmétique'],
    'tabs' => ['aria_label' => 'Sections du produit', 'formula' => 'Formule', 'packaging' => 'Conditionnement', 'costing' => 'Coûts', 'output' => 'Étiquette et rendu', 'instructions' => 'Instructions et médias'],
    'settings' => ['title' => 'Paramètres de la formule', 'hide' => 'Masquer les paramètres', 'edit' => 'Modifier les paramètres', 'total_oil_weight' => 'Poids total des huiles', 'entry_mode' => 'Saisir les quantités en', 'water_mode' => 'Calculer l’eau selon', 'product_use' => 'Utilisation du produit', 'regulatory_framework' => 'Cadre réglementaire', 'ifra_category' => 'Catégorie IFRA', 'no_ifra_category' => 'Aucune catégorie IFRA sélectionnée', 'ifra_unavailable' => 'Les catégories IFRA sont actuellement indisponibles.'],
    'ingredients' => ['title' => 'Ajouter des ingrédients', 'search_placeholder' => 'Rechercher par nom ou INCI', 'search_label' => 'Rechercher des ingrédients', 'count_singular' => '1 ingrédient', 'count_plural' => ':count ingrédients', 'properties' => 'Propriétés', 'ownership_note' => 'Les ingrédients créés ou modifiés par l’utilisateur sont signalés par un point. Soapkraft n’a pas vérifié leurs données.'],
    'saponification' => ['title' => 'Saponification', 'balanced' => 'Huiles à 100 %', 'unbalanced' => 'Les huiles doivent totaliser 100 %', 'lye_water' => 'Soude et eau', 'empty' => 'Ajoutez ou déposez une huile ici', 'total_oils' => 'Total des huiles', 'warning' => 'Les huiles doivent totaliser 100 % avant l’enregistrement.'],
    'additions' => ['title' => 'Ajouts à la formule', 'additives_help' => 'Colorants, conservateurs et autres ingrédients fonctionnels.', 'fragrance_help' => 'Parfums, huiles essentielles et extraits aromatiques.', 'empty_oil' => 'Déposez une huile ici pour l’utiliser comme ajout.', 'batch_totals' => 'Totaux du lot'],
    'qualities' => ['disclaimer' => 'Ces valeurs sont des estimations. Le procédé, les ajouts et les conditions de cure influencent le savon fini.', 'review_title' => 'Points à vérifier', 'empty' => 'Ajoutez des huiles avec des données SAP et d’acides gras pour calculer les qualités du savon.'],
    'fatty_acids' => ['details' => 'Acides gras individuels', 'empty' => 'Ajoutez des huiles avec des données d’acides gras pour afficher le profil du mélange.'],
    'status' => ['title' => 'État de la formule', 'oils' => 'Huiles', 'lye_water' => 'Soude et eau', 'missing_quantities' => 'Quantités manquantes', 'changes' => 'Modifications', 'ready' => 'Prêt à enregistrer.', 'amounts_calculated' => 'Quantités calculées.', 'waiting' => 'Ajoutez des huiles et complétez les paramètres.', 'zero_detail' => 'Ces ingrédients restent dans la formule jusqu’à la saisie de leurs quantités.', 'save_changes' => 'Enregistrez pour conserver ces modifications.', 'pending' => 'En attente', 'none' => 'Aucune', 'saved' => 'Enregistré', 'unsaved' => 'Non enregistré', 'saving' => 'Enregistrement', 'save_failed' => 'Échec de l’enregistrement', 'saved_detail' => 'Les modifications actuelles sont enregistrées.', 'saving_detail' => 'Enregistrement des modifications en cours.', 'balanced_remaining' => 'Il reste :amount % à équilibrer.', 'negative_superfat_warning' => 'Un surgraissage négatif laisse un excès de soude. Sans neutralisation et tests appropriés, le produit peut provoquer des irritations ou des brûlures. Continuer ?'],
];
