<?php

return [
    'headings' => ['soap_qualities' => 'Qualités Soapkraft', 'fatty_acid_profile' => 'Profil des acides gras'],
    'common' => ['ingredient' => 'Ingrédient', 'oil' => 'Huile', 'weight' => 'Poids', 'additives' => 'Ajouts', 'fragrance' => 'Parfums et aromatiques', 'fatty_acids' => 'Acides gras', 'lye_type' => 'Type de soude', 'dual_lye' => 'Soude mixte', 'superfat' => 'Surgraissage', 'rinse_off' => 'Produit rincé', 'leave_on' => 'Produit non rincé', 'product_category' => 'Catégorie de produit', 'choose_later' => 'Choisir plus tard', 'total_batch' => 'Quantité totale du lot', 'cosmetic_categories_unavailable' => 'Les catégories de produit sont actuellement indisponibles.', 'label_compliance' => 'Étiquette et conformité', 'water_percent' => 'Eau en % des huiles', 'water_ratio' => 'Rapport eau : soude', 'lye_concentration' => 'Concentration de soude', 'formula_percent' => '% de la formule'],
    'header' => ['section' => 'Produit', 'product_name' => 'Nom du produit', 'untitled_soap' => 'Savon sans titre', 'untitled_cosmetic' => 'Produit cosmétique sans titre', 'product_sheet' => 'Fiche produit', 'locked' => 'Verrouillé', 'saving' => 'Enregistrement…', 'save' => 'Enregistrer', 'lock_product' => 'Verrouiller le produit', 'unlock_product' => 'Déverrouiller le produit', 'more_actions' => 'Autres actions', 'product_details' => 'Détails du produit', 'duplicate_product' => 'Dupliquer le produit', 'new_product' => 'Nouveau produit', 'current_product' => 'Produit actuel', 'new_soap' => 'Nouveau savon', 'new_cosmetic' => 'Nouveau produit cosmétique'],
    'tabs' => ['aria_label' => 'Sections du produit', 'formula' => 'Formule', 'packaging' => 'Conditionnement', 'costing' => 'Coûts', 'output' => 'Étiquette et rendu', 'instructions' => 'Instructions et médias'],
    'settings' => ['title' => 'Paramètres de la formule', 'hide' => 'Masquer les paramètres', 'edit' => 'Modifier les paramètres', 'total_oil_weight' => 'Poids total des huiles', 'entry_mode' => 'Saisir les quantités en', 'water_mode' => 'Calculer l’eau selon', 'product_use' => 'Utilisation du produit', 'regulatory_framework' => 'Cadre réglementaire', 'ifra_category' => 'Catégorie IFRA', 'no_ifra_category' => 'Aucune catégorie IFRA sélectionnée', 'ifra_unavailable' => 'Les catégories IFRA sont actuellement indisponibles.'],
    'ingredients' => ['title' => 'Ajouter des ingrédients', 'search_placeholder' => 'Rechercher par nom ou INCI', 'search_label' => 'Rechercher des ingrédients', 'count_singular' => '1 ingrédient', 'count_plural' => ':count ingrédients', 'properties' => 'Propriétés', 'ownership_note' => 'Les ingrédients créés ou modifiés par l’utilisateur sont signalés par un point. Soapkraft n’a pas vérifié leurs données.'],
    'saponification' => ['title' => 'Saponification', 'balanced' => 'Huiles à 100 %', 'unbalanced' => 'Les huiles doivent totaliser 100 %', 'lye_water' => 'Soude et eau', 'empty' => 'Ajoutez ou déposez une huile ici', 'total_oils' => 'Total des huiles', 'warning' => 'Les huiles doivent totaliser 100 % avant l’enregistrement.'],
    'additions' => ['title' => 'Ajouts à la formule', 'additives_help' => 'Colorants, conservateurs et autres ingrédients fonctionnels.', 'fragrance_help' => 'Parfums, huiles essentielles et extraits aromatiques.', 'empty_oil' => 'Déposez une huile ici pour l’utiliser comme ajout.', 'batch_totals' => 'Totaux du lot'],
    'qualities' => ['disclaimer' => 'Ces valeurs sont des estimations. Le procédé, les ajouts et les conditions de cure influencent le savon fini.', 'review_title' => 'Points à vérifier', 'empty' => 'Ajoutez des huiles avec des données SAP et d’acides gras pour calculer les qualités du savon.'],
    'fatty_acids' => ['details' => 'Acides gras individuels', 'empty' => 'Ajoutez des huiles avec des données d’acides gras pour afficher le profil du mélange.'],
    'status' => ['title' => 'État de la formule', 'oils' => 'Huiles', 'lye_water' => 'Soude et eau', 'missing_quantities' => 'Quantités manquantes', 'changes' => 'Modifications', 'ready' => 'Prêt à enregistrer.', 'amounts_calculated' => 'Quantités calculées.', 'waiting' => 'Ajoutez des huiles et complétez les paramètres.', 'zero_detail' => 'Ces ingrédients restent dans la formule jusqu’à la saisie de leurs quantités.', 'save_changes' => 'Enregistrez pour conserver ces modifications.', 'pending' => 'En attente', 'none' => 'Aucune', 'saved' => 'Enregistré', 'unsaved' => 'Non enregistré', 'saving' => 'Enregistrement', 'save_failed' => 'Échec de l’enregistrement', 'saved_detail' => 'Les modifications actuelles sont enregistrées.', 'saving_detail' => 'Enregistrement des modifications en cours.', 'balanced_remaining' => 'Il reste :amount % à équilibrer.', 'negative_superfat_warning' => 'Un surgraissage négatif laisse un excès de soude. Sans neutralisation et tests appropriés, le produit peut provoquer des irritations ou des brûlures. Continuer ?'],
];
