<?php

return [
    'categories' => ['all' => 'Alle', 'carrier_oil' => 'Trägeröle', 'essential_oil' => 'Ätherische Öle', 'fragrance_oil' => 'Duftöle', 'botanical_extract' => 'Pflanzenextrakte', 'co2_extract' => 'CO2-Extrakte', 'liquid' => 'Flüssigkeiten', 'glycol' => 'Glykole', 'clay' => 'Tonmineralien', 'colorant' => 'Farbstoffe', 'preservative' => 'Konservierungsmittel', 'additive' => 'Zusätze'],
    'accessibility' => ['formula_save_bar' => 'Speicherleiste der Rezeptur', 'zero_quantity_note' => 'Zutaten mit der Menge null bleiben in der Rezeptur.', 'weight_unit' => 'Gewichtseinheit', 'entry_mode' => 'Eingabeart der Mengen', 'product_use' => 'Produktanwendung', 'filter_category' => 'Nach Kategorie filtern', 'ingredient_list' => 'Zutatenliste', 'user_owned' => 'Vom Benutzer erstellte oder geänderte Zutat', 'show_ingredient_details' => 'Zutatendetails anzeigen', 'ingredient_details' => 'Zutatendetails', 'add_ingredient' => 'Zutat hinzufügen', 'choose_phase' => 'Phase für diese Zutat auswählen'],
    'cosmetic' => ['title' => 'Rezepturbestandteile', 'instruction' => 'Zutaten nach Phasen ordnen und als Prozentwert oder Gewicht eingeben.', 'phase' => 'Phase', 'phase_name' => 'Phasenname', 'move_up' => 'Nach oben', 'move_down' => 'Nach unten', 'percent_of_formula' => ':percentage % der Rezeptur', 'remove_phase' => 'Phase entfernen', 'drop_here' => 'Zutaten hier ablegen', 'formula_total' => 'Rezeptur gesamt', 'add_phase' => 'Phase hinzufügen', 'formula_balanced' => 'Rezeptur ergibt 100 %', 'formula_unbalanced' => 'Rezeptur muss 100 % ergeben', 'balance_label' => 'Rezeptur gesamt', 'blend_only' => 'Nur mischen', 'category_label' => 'Kategorie', 'entry_label' => 'Mengen', 'exposure_label' => 'Produktanwendung', 'label_label' => 'Etikett', 'label_context' => 'Etikettierungsrahmen', 'quantity_complete_singular' => '1 Zutat hat eine Menge.', 'quantity_complete_plural' => ':count Zutaten haben Mengen.', 'no_screening_rules' => 'Für diesen Rechtsrahmen sind keine Prüfregeln hinterlegt.', 'allergen_singular' => ':count Allergen', 'allergen_plural' => ':count Allergene', 'substance_singular' => ':count Stoff', 'substance_plural' => ':count Stoffe', 'show' => 'Anzeigen', 'hide' => 'Ausblenden', 'show_details' => 'Details anzeigen', 'hide_details' => 'Details ausblenden', 'weight_with_unit' => 'Gewicht (:unit)', 'add_to_phase' => 'Zu :phase hinzufügen', 'drag_ingredient' => 'Ziehen, um diese Zutat neu anzuordnen', 'show_ingredient_details' => 'Zutatendetails anzeigen', 'remove_ingredient' => 'Zutat entfernen', 'percentage_for' => 'Prozentanteil für :ingredient', 'weight_for' => 'Gewicht für :ingredient'],
    'headings' => ['soap_qualities' => 'Soapkraft-Eigenschaften', 'fatty_acid_profile' => 'Fettsäureprofil'],
    'common' => ['ingredient' => 'Zutat', 'oil' => 'Öl', 'weight' => 'Gewicht', 'additives' => 'Zusätze', 'fragrance' => 'Duft und Aromen', 'fatty_acids' => 'Fettsäuren', 'lye_type' => 'Laugenart', 'dual_lye' => 'Mischlauge', 'superfat' => 'Überfettung', 'rinse_off' => 'Abspülprodukt', 'leave_on' => 'Verbleibendes Produkt', 'product_category' => 'Produktkategorie', 'choose_later' => 'Später auswählen', 'total_batch' => 'Gesamtmenge der Charge', 'cosmetic_categories_unavailable' => 'Produktkategorien sind derzeit nicht verfügbar.', 'label_compliance' => 'Etikett und Konformität', 'water_percent' => 'Wasser in % der Öle', 'water_ratio' => 'Verhältnis Wasser : Lauge', 'lye_concentration' => 'Laugenkonzentration', 'formula_percent' => '% der Rezeptur'],
    'header' => ['breadcrumb' => 'Produktnavigation', 'save_before_locking' => 'Speichern Sie das Produkt, bevor Sie es sperren.', 'section' => 'Produkt', 'product_name' => 'Produktname', 'untitled_soap' => 'Unbenannte Seife', 'untitled_cosmetic' => 'Unbenanntes Kosmetikprodukt', 'product_sheet' => 'Produktblatt', 'locked' => 'Gesperrt', 'saving' => 'Speichern…', 'save' => 'Speichern', 'lock_product' => 'Produkt sperren', 'unlock_product' => 'Produkt entsperren', 'more_actions' => 'Weitere Aktionen', 'product_details' => 'Produktdetails', 'duplicate_product' => 'Produkt duplizieren', 'new_product' => 'Neues Produkt', 'current_product' => 'Aktuelles Produkt', 'new_soap' => 'Neue Seife', 'new_cosmetic' => 'Neues Kosmetikprodukt'],
    'tabs' => ['aria_label' => 'Produktbereiche', 'formula' => 'Rezeptur', 'packaging' => 'Verpackung', 'costing' => 'Kosten', 'output' => 'Etikett & Ausgabe', 'instructions' => 'Anleitung & Medien'],
    'settings' => ['title' => 'Rezeptureinstellungen', 'hide' => 'Einstellungen ausblenden', 'edit' => 'Einstellungen bearbeiten', 'total_oil_weight' => 'Gesamtgewicht der Öle', 'entry_mode' => 'Mengen eingeben als', 'water_mode' => 'Wasser berechnen nach', 'product_use' => 'Produktanwendung', 'regulatory_framework' => 'Rechtsrahmen', 'ifra_category' => 'IFRA-Kategorie', 'no_ifra_category' => 'Keine IFRA-Kategorie ausgewählt', 'ifra_unavailable' => 'IFRA-Kategorien sind derzeit nicht verfügbar.'],
    'ingredients' => ['title' => 'Zutaten hinzufügen', 'search_placeholder' => 'Nach Name oder INCI suchen', 'search_label' => 'Zutaten suchen', 'count_singular' => '1 Zutat', 'count_plural' => ':count Zutaten', 'properties' => 'Eigenschaften', 'ownership_note' => 'Von Benutzern erstellte oder geänderte Zutaten sind mit einem Punkt gekennzeichnet. Soapkraft hat ihre Daten nicht geprüft.'],
    'saponification' => ['title' => 'Verseifung', 'balanced' => 'Öle ergeben 100 %', 'unbalanced' => 'Öle müssen 100 % ergeben', 'lye_water' => 'Lauge und Wasser', 'empty' => 'Öl hier hinzufügen oder ablegen', 'total_oils' => 'Öle gesamt', 'warning' => 'Die Öle müssen vor dem Speichern 100 % ergeben.'],
    'additions' => ['title' => 'Rezepturzusätze', 'additives_help' => 'Farbstoffe, Konservierungsmittel und weitere funktionelle Zutaten.', 'fragrance_help' => 'Duftöle, ätherische Öle und aromatische Extrakte.', 'empty_oil' => 'Öl hier ablegen, um es als Zusatz zu verwenden.', 'batch_totals' => 'Chargensummen'],
    'qualities' => ['disclaimer' => 'Diese Werte sind Schätzungen. Verfahren, Zusätze und Reifebedingungen beeinflussen die fertige Seife.', 'review_title' => 'Zu prüfende Punkte', 'empty' => 'Öle mit SAP- und Fettsäuredaten hinzufügen, um die Seifeneigenschaften zu berechnen.'],
    'fatty_acids' => ['details' => 'Einzelne Fettsäuren', 'empty' => 'Öle mit Fettsäuredaten hinzufügen, um das Mischprofil anzuzeigen.'],
    'status' => ['title' => 'Rezepturstatus', 'oils' => 'Öle', 'lye_water' => 'Lauge und Wasser', 'missing_quantities' => 'Fehlende Mengen', 'changes' => 'Änderungen', 'ready' => 'Bereit zum Speichern.', 'amounts_calculated' => 'Mengen berechnet.', 'waiting' => 'Öle hinzufügen und Einstellungen vervollständigen.', 'zero_detail' => 'Diese Zutaten bleiben in der Rezeptur, bis Mengen eingetragen werden.', 'save_changes' => 'Speichern, um diese Änderungen zu behalten.', 'pending' => 'Ausstehend', 'none' => 'Keine', 'saved' => 'Gespeichert', 'unsaved' => 'Nicht gespeichert', 'saving' => 'Wird gespeichert', 'save_failed' => 'Speichern fehlgeschlagen', 'saved_detail' => 'Die aktuellen Änderungen sind gespeichert.', 'saving_detail' => 'Die aktuellen Änderungen werden gespeichert.', 'balanced_remaining' => 'Noch :amount % auszugleichen.', 'negative_superfat_warning' => 'Eine negative Überfettung hinterlässt überschüssige Lauge. Ohne fachgerechte Neutralisation und Prüfung kann das Produkt Reizungen oder Verätzungen verursachen. Fortfahren?'],
];
