<x-production-bench.page compact>
    <header class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
        <div>
            <p class="sk-eyebrow">{{ __('production_bench.navigation.production') }}</p>
            <h1 class="mt-2 text-3xl font-semibold text-[var(--color-ink-strong)]">{{ __('production_bench.settings.title') }}</h1>
            <p class="mt-2 max-w-2xl text-sm text-[var(--color-ink-soft)]">{{ __('production_bench.settings.intro') }}</p>
        </div>
        @if ($isReadOnly)
            <p role="status" class="rounded-xl bg-[var(--color-warning-soft)] px-4 py-3 text-sm text-[var(--color-warning-strong)]">{{ __('production_bench.common.read_only') }}</p>
        @elseif (! $isBenchActive)
            <p role="status" class="rounded-xl bg-[var(--color-panel-muted)] px-4 py-3 text-sm text-[var(--color-ink-soft)]">{{ __('production_bench.common.inactive') }}</p>
        @endif
    </header>

    <section aria-labelledby="preset-heading" class="space-y-4">
        <div>
            <h2 id="preset-heading" class="text-xl font-semibold text-[var(--color-ink-strong)]">{{ __('production_bench.settings.presets') }}</h2>
            <p class="mt-1 text-sm text-[var(--color-ink-soft)]">{{ __('production_bench.settings.presets_help') }}</p>
        </div>
        <form wire:submit="savePreset" class="sk-card grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-4">
            <label class="text-sm"><span class="font-medium">{{ __('production_bench.settings.product') }}</span><select wire:model="presetRecipeId" class="sk-input mt-1 w-full" @disabled(! $isBenchActive || $isReadOnly)><option value="">{{ __('production_bench.settings.choose_product') }}</option>@foreach ($recipes as $recipe)<option value="{{ $recipe->id }}">{{ $recipe->name }}</option>@endforeach</select>@error('presetRecipeId')<span class="mt-1 block text-xs text-[var(--color-danger-strong)]">{{ $message }}</span>@enderror</label>
            <label class="text-sm"><span class="font-medium">{{ __('production_bench.settings.preset_name') }}</span><input wire:model="presetName" class="sk-input mt-1 w-full" placeholder="12 kg oils / 100 units" @disabled(! $isBenchActive || $isReadOnly)>@error('presetName')<span class="mt-1 block text-xs text-[var(--color-danger-strong)]">{{ $message }}</span>@enderror</label>
            <label class="text-sm"><span class="font-medium">{{ __('production_bench.settings.batch_size') }}</span><span class="mt-1 flex gap-2"><input wire:model="presetBasisInputValue" type="number" min="0.001" step="0.001" class="sk-input min-w-0 flex-1" placeholder="12" @disabled(! $isBenchActive || $isReadOnly)><select wire:model="presetBasisInputUnit" class="sk-input w-24" @disabled(! $isBenchActive || $isReadOnly)>@foreach ($massUnits as $unit)<option value="{{ $unit->value }}">{{ $unit->value }}</option>@endforeach</select></span>@error('presetBasisInputValue')<span class="mt-1 block text-xs text-[var(--color-danger-strong)]">{{ $message }}</span>@enderror</label>
            <label class="text-sm"><span class="font-medium">{{ __('production_bench.settings.expected_units') }}</span><input wire:model="presetExpectedUnits" type="number" min="1" step="1" class="sk-input mt-1 w-full" placeholder="100" @disabled(! $isBenchActive || $isReadOnly)>@error('presetExpectedUnits')<span class="mt-1 block text-xs text-[var(--color-danger-strong)]">{{ $message }}</span>@enderror</label>
            <label class="flex items-center gap-2 text-sm md:col-span-2"><input wire:model="presetIsDefault" type="checkbox" class="size-4 rounded accent-[var(--color-accent)]" @disabled(! $isBenchActive || $isReadOnly)>{{ __('production_bench.settings.default_for_product') }}</label>
            <div class="flex items-center gap-2 xl:col-span-2 xl:justify-end"><button type="button" wire:click="resetPresetForm" class="sk-btn sk-btn-ghost" @disabled(! $isBenchActive || $isReadOnly)>{{ __('production_bench.common.clear') }}</button><button type="submit" class="sk-btn sk-btn-primary" @disabled(! $isBenchActive || $isReadOnly)>{{ $editingPresetId ? __('production_bench.common.save_changes') : __('production_bench.settings.add_preset') }}</button></div>
        </form>
        <div class="overflow-x-auto rounded-2xl border border-[var(--color-line)] bg-[var(--color-panel)]">
            <table class="w-full min-w-[700px] text-left text-sm"><thead class="bg-[var(--color-panel-muted)] text-xs uppercase tracking-wide text-[var(--color-ink-soft)]"><tr><th class="px-5 py-3">{{ __('production_bench.settings.product') }}</th><th class="px-4 py-3">{{ __('production_bench.settings.batch_size') }}</th><th class="px-4 py-3">{{ __('production_bench.settings.expected_units') }}</th><th class="px-4 py-3">{{ __('production_bench.common.status') }}</th><th class="px-5 py-3 text-right">{{ __('production_bench.common.actions') }}</th></tr></thead><tbody class="divide-y divide-[var(--color-line)]">@forelse ($presets as $preset)<tr wire:key="preset-{{ $preset->id }}"><td class="px-5 py-4 font-medium text-[var(--color-ink-strong)]">{{ $preset->recipe?->name }} @if($preset->is_default)<span class="ml-2 rounded-full bg-[var(--color-accent-soft)] px-2 py-1 text-xs text-[var(--color-accent-strong)]">{{ __('production_bench.settings.default') }}</span>@endif</td><td class="px-4 py-4">{{ $preset->basis_input_value }} {{ $preset->basis_input_unit->value }}</td><td class="numeric px-4 py-4">{{ $preset->expected_units }}</td><td class="px-4 py-4">{{ $preset->is_active ? __('production_bench.common.active') : __('production_bench.common.inactive') }}</td><td class="px-5 py-4 text-right"><button type="button" wire:click="editPreset({{ $preset->id }})" class="text-[var(--color-accent-strong)] hover:underline" @disabled(! $isBenchActive || $isReadOnly)>{{ __('production_bench.common.edit') }}</button></td></tr>@empty<tr><td colspan="5" class="px-5 py-8 text-center text-sm text-[var(--color-ink-soft)]">{{ __('production_bench.settings.no_presets') }}</td></tr>@endforelse</tbody></table>
        </div>
    </section>

    <div class="grid gap-8 lg:grid-cols-2">
        <section aria-labelledby="employee-heading" class="space-y-4">
            <div><h2 id="employee-heading" class="text-xl font-semibold text-[var(--color-ink-strong)]">{{ __('production_bench.settings.employees') }}</h2><p class="mt-1 text-sm text-[var(--color-ink-soft)]">{{ __('production_bench.settings.employees_help') }}</p></div>
            <form wire:submit="saveEmployee" class="sk-card grid gap-4 p-5 sm:grid-cols-2">
                <label class="text-sm"><span class="font-medium">{{ __('production_bench.settings.first_name') }}</span><input wire:model="employeeFirstName" class="sk-input mt-1 w-full" autocomplete="given-name" @disabled(! $isBenchActive || $isReadOnly)>@error('employeeFirstName')<span class="mt-1 block text-xs text-[var(--color-danger-strong)]">{{ $message }}</span>@enderror</label>
                <label class="text-sm"><span class="font-medium">{{ __('production_bench.settings.last_name') }}</span><input wire:model="employeeLastName" class="sk-input mt-1 w-full" autocomplete="family-name" @disabled(! $isBenchActive || $isReadOnly)>@error('employeeLastName')<span class="mt-1 block text-xs text-[var(--color-danger-strong)]">{{ $message }}</span>@enderror</label>
                <label class="flex items-center gap-2 text-sm sm:col-span-2"><input wire:model="employeeIsActive" type="checkbox" class="size-4 rounded accent-[var(--color-accent)]" @disabled(! $isBenchActive || $isReadOnly)>{{ __('production_bench.common.active') }}</label>
                <div class="flex gap-2 sm:col-span-2"><button type="button" wire:click="resetEmployeeForm" class="sk-btn sk-btn-ghost" @disabled(! $isBenchActive || $isReadOnly)>{{ __('production_bench.common.clear') }}</button><button type="submit" class="sk-btn sk-btn-primary" @disabled(! $isBenchActive || $isReadOnly)>{{ $editingEmployeeId ? __('production_bench.common.save_changes') : __('production_bench.settings.add_employee') }}</button></div>
            </form>
            <div class="sk-card divide-y divide-[var(--color-line)] p-1">@forelse ($employees as $employee)<div wire:key="employee-{{ $employee->id }}" class="flex items-center justify-between gap-3 p-4"><span><span class="block font-medium text-[var(--color-ink-strong)]">{{ $employee->first_name }} {{ $employee->last_name }}</span><span class="text-xs text-[var(--color-ink-soft)]">{{ $employee->is_active ? __('production_bench.common.active') : __('production_bench.common.inactive') }}</span></span><button type="button" wire:click="editEmployee({{ $employee->id }})" class="text-sm text-[var(--color-accent-strong)] hover:underline" @disabled(! $isBenchActive || $isReadOnly)>{{ __('production_bench.common.edit') }}</button></div>@empty<p class="p-5 text-sm text-[var(--color-ink-soft)]">{{ __('production_bench.settings.no_employees') }}</p>@endforelse</div>
        </section>

        <section aria-labelledby="task-type-heading" class="space-y-4">
            <div><h2 id="task-type-heading" class="text-xl font-semibold text-[var(--color-ink-strong)]">{{ __('production_bench.settings.task_types') }}</h2><p class="mt-1 text-sm text-[var(--color-ink-soft)]">{{ __('production_bench.settings.task_types_help') }}</p></div>
            <form wire:submit="saveTaskType" class="sk-card grid gap-4 p-5 sm:grid-cols-2">
                <label class="text-sm sm:col-span-2"><span class="font-medium">{{ __('production_bench.settings.task_name') }}</span><input wire:model="taskTypeName" class="sk-input mt-1 w-full" placeholder="Pour and cut" @disabled(! $isBenchActive || $isReadOnly)>@error('taskTypeName')<span class="mt-1 block text-xs text-[var(--color-danger-strong)]">{{ $message }}</span>@enderror</label>
                <label class="text-sm"><span class="font-medium">{{ __('production_bench.settings.duration_minutes') }}</span><input wire:model="taskTypeDuration" type="number" min="0" step="1" class="sk-input mt-1 w-full" @disabled(! $isBenchActive || $isReadOnly)></label>
                <label class="text-sm"><span class="font-medium">{{ __('production_bench.settings.colour') }}</span><input wire:model="taskTypeColour" type="text" class="sk-input mt-1 w-full" placeholder="#8F5C38" @disabled(! $isBenchActive || $isReadOnly)></label>
                <div class="flex items-center gap-2 text-sm sm:col-span-2"><input wire:model="taskTypeIsActive" type="checkbox" class="size-4 rounded accent-[var(--color-accent)]" @disabled(! $isBenchActive || $isReadOnly)>{{ __('production_bench.common.active') }}</div>
                <div class="flex gap-2 sm:col-span-2"><button type="button" wire:click="resetTaskTypeForm" class="sk-btn sk-btn-ghost" @disabled(! $isBenchActive || $isReadOnly)>{{ __('production_bench.common.clear') }}</button><button type="submit" class="sk-btn sk-btn-primary" @disabled(! $isBenchActive || $isReadOnly)>{{ $editingTaskTypeId ? __('production_bench.common.save_changes') : __('production_bench.settings.add_task_type') }}</button></div>
            </form>
            <div class="sk-card divide-y divide-[var(--color-line)] p-1">@forelse ($taskTypes as $taskType)<div wire:key="task-type-{{ $taskType->id }}" class="flex items-center justify-between gap-3 p-4"><span><span class="block font-medium text-[var(--color-ink-strong)]">{{ $taskType->name }}</span><span class="text-xs text-[var(--color-ink-soft)]">{{ $taskType->default_duration_minutes ? $taskType->default_duration_minutes.' min · ' : '' }}{{ $taskType->is_active ? __('production_bench.common.active') : __('production_bench.common.inactive') }}</span></span><button type="button" wire:click="editTaskType({{ $taskType->id }})" class="text-sm text-[var(--color-accent-strong)] hover:underline" @disabled(! $isBenchActive || $isReadOnly)>{{ __('production_bench.common.edit') }}</button></div>@empty<p class="p-5 text-sm text-[var(--color-ink-soft)]">{{ __('production_bench.settings.no_task_types') }}</p>@endforelse</div>
        </section>
    </div>

    <section aria-labelledby="task-set-heading" class="space-y-4">
        <div><h2 id="task-set-heading" class="text-xl font-semibold text-[var(--color-ink-strong)]">{{ __('production_bench.settings.task_sets') }}</h2><p class="mt-1 text-sm text-[var(--color-ink-soft)]">{{ __('production_bench.settings.task_sets_help') }}</p></div>
        <form wire:submit="saveTaskSet" class="sk-card space-y-4 p-5">
            <div class="grid gap-4 md:grid-cols-3"><label class="text-sm"><span class="font-medium">{{ __('production_bench.settings.task_set_name') }}</span><input wire:model="taskSetName" class="sk-input mt-1 w-full" placeholder="Soap workflow" @disabled(! $isBenchActive || $isReadOnly)>@error('taskSetName')<span class="mt-1 block text-xs text-[var(--color-danger-strong)]">{{ $message }}</span>@enderror</label><label class="text-sm"><span class="font-medium">{{ __('production_bench.settings.default_product') }}</span><select wire:model="taskSetRecipeId" class="sk-input mt-1 w-full" @disabled(! $isBenchActive || $isReadOnly)><option value="">{{ __('production_bench.settings.no_default_product') }}</option>@foreach ($recipes as $recipe)<option value="{{ $recipe->id }}">{{ $recipe->name }}</option>@endforeach</select></label><label class="flex items-center gap-2 self-end pb-2 text-sm"><input wire:model="taskSetIsDefault" type="checkbox" class="size-4 rounded accent-[var(--color-accent)]" @disabled(! $isBenchActive || $isReadOnly)>{{ __('production_bench.settings.default_for_product') }}</label></div>
            <div class="space-y-3"><div class="grid gap-2 text-xs font-semibold uppercase tracking-wide text-[var(--color-ink-soft)] sm:grid-cols-[minmax(0,1fr)_10rem_10rem_auto]"><span>{{ __('production_bench.settings.task_name') }}</span><span>{{ __('production_bench.settings.days_after_production') }}</span><span>{{ __('production_bench.settings.duration_minutes') }}</span><span class="sr-only">{{ __('production_bench.common.actions') }}</span></div>@foreach ($taskSetItems as $index => $item)<div wire:key="task-set-item-{{ $index }}" class="grid gap-2 sm:grid-cols-[minmax(0,1fr)_10rem_10rem_auto]"><select wire:model="taskSetItems.{{ $index }}.task_type_id" class="sk-input w-full" @disabled(! $isBenchActive || $isReadOnly)><option value="">{{ __('production_bench.settings.choose_task') }}</option>@foreach ($taskTypes as $taskType)<option value="{{ $taskType->id }}">{{ $taskType->name }}</option>@endforeach</select><input wire:model="taskSetItems.{{ $index }}.days_after_production" type="number" min="0" step="1" class="sk-input w-full" @disabled(! $isBenchActive || $isReadOnly)><input wire:model="taskSetItems.{{ $index }}.duration_minutes" type="number" min="0" step="1" class="sk-input w-full" placeholder="{{ __('production_bench.settings.default') }}" @disabled(! $isBenchActive || $isReadOnly)><button type="button" wire:click="removeTaskSetItem({{ $index }})" class="sk-btn sk-btn-ghost" @disabled(! $isBenchActive || $isReadOnly || count($taskSetItems) <= 1) aria-label="{{ __('production_bench.settings.remove_task') }}">×</button></div>@endforeach</div>
            <div class="flex flex-wrap items-center justify-between gap-3"><button type="button" wire:click="addTaskSetItem" class="text-sm font-medium text-[var(--color-accent-strong)] hover:underline" @disabled(! $isBenchActive || $isReadOnly)>+ {{ __('production_bench.settings.add_task') }}</button><div class="flex gap-2"><button type="button" wire:click="resetTaskSetForm" class="sk-btn sk-btn-ghost" @disabled(! $isBenchActive || $isReadOnly)>{{ __('production_bench.common.clear') }}</button><button type="submit" class="sk-btn sk-btn-primary" @disabled(! $isBenchActive || $isReadOnly)>{{ $editingTaskSetId ? __('production_bench.common.save_changes') : __('production_bench.settings.add_task_set') }}</button></div></div>
        </form>
        <div class="grid gap-3 md:grid-cols-2">@forelse ($taskSets as $taskSet)<article wire:key="task-set-{{ $taskSet->id }}" class="sk-card p-5"><div class="flex items-start justify-between gap-3"><div><h3 class="font-semibold text-[var(--color-ink-strong)]">{{ $taskSet->name }}</h3><p class="mt-1 text-xs text-[var(--color-ink-soft)]">{{ $taskSet->items->map(fn ($item): string => $item->taskType?->name ?? '—')->join(' · ') }}</p></div><button type="button" wire:click="editTaskSet({{ $taskSet->id }})" class="text-sm text-[var(--color-accent-strong)] hover:underline" @disabled(! $isBenchActive || $isReadOnly)>{{ __('production_bench.common.edit') }}</button></div></article>@empty<p class="sk-card p-5 text-sm text-[var(--color-ink-soft)]">{{ __('production_bench.settings.no_task_sets') }}</p>@endforelse</div>
    </section>

    <div class="grid gap-8 lg:grid-cols-[minmax(0,1fr)_minmax(18rem,.65fr)]">
        <section aria-labelledby="holiday-heading" class="space-y-4">
            <div><h2 id="holiday-heading" class="text-xl font-semibold text-[var(--color-ink-strong)]">{{ __('production_bench.settings.working_calendar') }}</h2><p class="mt-1 text-sm text-[var(--color-ink-soft)]">{{ __('production_bench.settings.working_calendar_help') }}</p></div>
            <form wire:submit="saveHoliday" class="sk-card grid gap-4 p-5 sm:grid-cols-[minmax(0,1fr)_12rem_auto]"><label class="text-sm"><span class="font-medium">{{ __('production_bench.settings.holiday_name') }}</span><input wire:model="holidayName" class="sk-input mt-1 w-full" placeholder="Summer closure" @disabled(! $isBenchActive || $isReadOnly)>@error('holidayName')<span class="mt-1 block text-xs text-[var(--color-danger-strong)]">{{ $message }}</span>@enderror</label><label class="text-sm"><span class="font-medium">{{ __('production_bench.settings.holiday_date') }}</span><input wire:model="holidayDate" type="date" class="sk-input mt-1 w-full" @disabled(! $isBenchActive || $isReadOnly)>@error('holidayDate')<span class="mt-1 block text-xs text-[var(--color-danger-strong)]">{{ $message }}</span>@enderror</label><label class="flex items-center gap-2 self-end pb-2 text-sm"><input wire:model="holidayIsRecurring" type="checkbox" class="size-4 rounded accent-[var(--color-accent)]" @disabled(! $isBenchActive || $isReadOnly)>{{ __('production_bench.settings.recurring') }}</label><button type="submit" class="sk-btn sk-btn-primary sm:col-span-3 sm:justify-self-end" @disabled(! $isBenchActive || $isReadOnly)>{{ __('production_bench.settings.add_holiday') }}</button></form>
            <div class="sk-card divide-y divide-[var(--color-line)] p-1">@forelse ($holidays as $holiday)<div wire:key="holiday-{{ $holiday->id }}" class="flex items-center justify-between gap-3 p-4"><span><span class="block font-medium text-[var(--color-ink-strong)]">{{ $holiday->name }}</span><span class="text-xs text-[var(--color-ink-soft)]">{{ $holiday->date->format('d/m/Y') }}{{ $holiday->is_recurring ? ' · '.__('production_bench.settings.recurring') : '' }}</span></span></div>@empty<p class="p-5 text-sm text-[var(--color-ink-soft)]">{{ __('production_bench.settings.no_holidays') }}</p>@endforelse</div>
        </section>
        <section aria-labelledby="weekend-heading" class="space-y-4"><div><h2 id="weekend-heading" class="text-xl font-semibold text-[var(--color-ink-strong)]">{{ __('production_bench.settings.weekends') }}</h2><p class="mt-1 text-sm text-[var(--color-ink-soft)]">{{ __('production_bench.settings.weekends_help') }}</p></div><div class="sk-card p-5"><label class="flex items-start gap-3 text-sm"><input wire:model="worksOnWeekends" wire:change="saveCalendar" type="checkbox" class="mt-0.5 size-4 rounded accent-[var(--color-accent)]" @disabled(! $isBenchActive || $isReadOnly)><span><span class="font-medium text-[var(--color-ink-strong)]">{{ __('production_bench.settings.works_on_weekends') }}</span><span class="mt-1 block text-[var(--color-ink-soft)]">{{ __('production_bench.settings.works_on_weekends_help') }}</span></span></label></div></section>
    </div>
</x-production-bench.page>
