<?php

return [
    'categories' => ['all' => 'Alle', 'carrier_oil' => 'Draagoliën', 'essential_oil' => 'Etherische oliën', 'fragrance_oil' => 'Parfumoliën', 'botanical_extract' => 'Plantenextracten', 'co2_extract' => 'CO2-extracten', 'liquid' => 'Vloeistoffen', 'glycol' => 'Glycolen', 'clay' => 'Kleisoorten', 'colorant' => 'Kleurstoffen', 'preservative' => 'Conserveermiddelen', 'additive' => 'Toevoegingen'],
    'accessibility' => ['formula_save_bar' => 'Opslagbalk van de formule', 'zero_quantity_note' => 'Ingrediënten met hoeveelheid nul blijven in de formule staan.', 'weight_unit' => 'Gewichtseenheid', 'entry_mode' => 'Invoerwijze voor hoeveelheden', 'product_use' => 'Productgebruik', 'filter_category' => 'Filteren op categorie', 'ingredient_list' => 'Ingrediëntenlijst', 'user_owned' => 'Door de gebruiker gemaakt of gewijzigd ingrediënt', 'show_ingredient_details' => 'Ingrediëntgegevens tonen', 'ingredient_details' => 'Ingrediëntgegevens', 'add_ingredient' => 'Ingrediënt toevoegen', 'choose_phase' => 'Kies een fase voor dit ingrediënt'],
    'cosmetic' => ['title' => 'Formule-ingrediënten', 'instruction' => 'Deel ingrediënten in per fase en voer daarna een percentage of gewicht in.', 'phase' => 'Fase', 'phase_name' => 'Fasenaam', 'move_up' => 'Omhoog', 'move_down' => 'Omlaag', 'percent_of_formula' => ':percentage% van de formule', 'remove_phase' => 'Fase verwijderen', 'drop_here' => 'Sleep ingrediënten hierheen', 'formula_total' => 'Formuletotaal', 'add_phase' => 'Fase toevoegen', 'formula_balanced' => 'Formule is samen 100%', 'formula_unbalanced' => 'Formule moet samen 100% zijn', 'balance_label' => 'Formuletotaal', 'blend_only' => 'Alleen mengen', 'category_label' => 'Categorie', 'entry_label' => 'Hoeveelheden', 'exposure_label' => 'Productgebruik', 'label_label' => 'Etiket', 'label_context' => 'Etiketteringskader', 'quantity_complete_singular' => '1 ingrediënt heeft een hoeveelheid.', 'quantity_complete_plural' => ':count ingrediënten hebben hoeveelheden.', 'no_screening_rules' => 'Voor dit regelgevingskader zijn geen controleregels beschikbaar.', 'allergen_singular' => ':count allergeen', 'allergen_plural' => ':count allergenen', 'substance_singular' => ':count stof', 'substance_plural' => ':count stoffen', 'show' => 'Tonen', 'hide' => 'Verbergen', 'show_details' => 'Details tonen', 'hide_details' => 'Details verbergen', 'weight_with_unit' => 'Gewicht (:unit)', 'add_to_phase' => 'Toevoegen aan :phase', 'drag_ingredient' => 'Sleep om dit ingrediënt opnieuw te ordenen', 'show_ingredient_details' => 'Ingrediëntgegevens tonen', 'remove_ingredient' => 'Ingrediënt verwijderen', 'percentage_for' => 'Percentage voor :ingredient', 'weight_for' => 'Gewicht voor :ingredient'],
    'headings' => ['soap_qualities' => 'Soapkraft-eigenschappen', 'fatty_acid_profile' => 'Vetzuurprofiel'],
    'common' => ['ingredient' => 'Ingrediënt', 'oil' => 'Olie', 'weight' => 'Gewicht', 'additives' => 'Toevoegingen', 'fragrance' => 'Geur en aroma’s', 'fatty_acids' => 'Vetzuren', 'lye_type' => 'Soort loog', 'dual_lye' => 'Gemengde loog', 'superfat' => 'Overvetting', 'rinse_off' => 'Afspoelproduct', 'leave_on' => 'Niet-afspoelbaar product', 'product_category' => 'Productcategorie', 'choose_later' => 'Later kiezen', 'total_batch' => 'Totale batchhoeveelheid', 'cosmetic_categories_unavailable' => 'Productcategorieën zijn momenteel niet beschikbaar.', 'label_compliance' => 'Etiket en regelgeving', 'water_percent' => 'Water als % van de oliën', 'water_ratio' => 'Verhouding water : loog', 'lye_concentration' => 'Loogconcentratie', 'formula_percent' => '% van de formule'],
    'header' => ['breadcrumb' => 'Productnavigatie', 'save_before_locking' => 'Sla het product op voordat je het vergrendelt.', 'section' => 'Product', 'product_name' => 'Productnaam', 'untitled_soap' => 'Naamloze zeep', 'untitled_cosmetic' => 'Naamloos cosmeticaproduct', 'product_sheet' => 'Productblad', 'locked' => 'Vergrendeld', 'saving' => 'Opslaan…', 'save' => 'Opslaan', 'lock_product' => 'Product vergrendelen', 'unlock_product' => 'Product ontgrendelen', 'more_actions' => 'Meer acties', 'product_details' => 'Productgegevens', 'duplicate_product' => 'Product dupliceren', 'new_product' => 'Nieuw product', 'current_product' => 'Huidig product', 'new_soap' => 'Nieuwe zeep', 'new_cosmetic' => 'Nieuw cosmeticaproduct'],
    'tabs' => ['aria_label' => 'Productonderdelen', 'formula' => 'Formule', 'packaging' => 'Verpakking', 'costing' => 'Kosten', 'output' => 'Etiket en uitvoer', 'instructions' => 'Instructies en media'],
    'settings' => ['title' => 'Formule-instellingen', 'hide' => 'Instellingen verbergen', 'edit' => 'Instellingen bewerken', 'total_oil_weight' => 'Totaalgewicht van de oliën', 'entry_mode' => 'Hoeveelheden invoeren als', 'water_mode' => 'Water berekenen op basis van', 'product_use' => 'Productgebruik', 'regulatory_framework' => 'Regelgevingskader', 'ifra_category' => 'IFRA-categorie', 'no_ifra_category' => 'Geen IFRA-categorie geselecteerd', 'ifra_unavailable' => 'IFRA-categorieën zijn momenteel niet beschikbaar.'],
    'ingredients' => ['title' => 'Ingrediënten toevoegen', 'search_placeholder' => 'Zoeken op naam of INCI', 'search_label' => 'Ingrediënten zoeken', 'count_singular' => '1 ingrediënt', 'count_plural' => ':count ingrediënten', 'properties' => 'Eigenschappen', 'ownership_note' => 'Door gebruikers gemaakte of gewijzigde ingrediënten zijn gemarkeerd met een punt. Soapkraft heeft de gegevens niet gecontroleerd.'],
    'saponification' => ['title' => 'Verzeping', 'balanced' => 'Oliën vormen 100%', 'unbalanced' => 'Oliën moeten samen 100% zijn', 'lye_water' => 'Loog en water', 'empty' => 'Voeg hier een olie toe of sleep deze hierheen', 'total_oils' => 'Totaal oliën', 'warning' => 'De oliën moeten samen 100% zijn voordat je opslaat.'],
    'additions' => ['title' => 'Formuletoevoegingen', 'additives_help' => 'Kleurstoffen, conserveermiddelen en andere functionele ingrediënten.', 'fragrance_help' => 'Parfumoliën, etherische oliën en aromatische extracten.', 'empty_oil' => 'Sleep hier een olie heen om deze als toevoeging te gebruiken.', 'batch_totals' => 'Batchtotalen'],
    'qualities' => ['disclaimer' => 'Deze waarden zijn schattingen. Het proces, de toevoegingen en de rijpingsomstandigheden beïnvloeden de uiteindelijke zeep.', 'review_title' => 'Aandachtspunten', 'empty' => 'Voeg oliën met SAP- en vetzuurgegevens toe om de zeepeigenschappen te berekenen.'],
    'fatty_acids' => ['details' => 'Afzonderlijke vetzuren', 'empty' => 'Voeg oliën met vetzuurgegevens toe om het mengprofiel te bekijken.'],
    'status' => ['title' => 'Formulestatus', 'oils' => 'Oliën', 'lye_water' => 'Loog en water', 'missing_quantities' => 'Ontbrekende hoeveelheden', 'changes' => 'Wijzigingen', 'ready' => 'Klaar om op te slaan.', 'amounts_calculated' => 'Hoeveelheden berekend.', 'waiting' => 'Voeg oliën toe en rond de instellingen af.', 'zero_detail' => 'Deze ingrediënten blijven in de formule staan totdat je hoeveelheden invult.', 'save_changes' => 'Sla op om deze wijzigingen te bewaren.', 'pending' => 'In afwachting', 'none' => 'Geen', 'saved' => 'Opgeslagen', 'unsaved' => 'Niet opgeslagen', 'saving' => 'Opslaan', 'save_failed' => 'Opslaan mislukt', 'saved_detail' => 'De huidige wijzigingen zijn opgeslagen.', 'saving_detail' => 'De huidige wijzigingen worden opgeslagen.', 'balanced_remaining' => 'Nog :amount% te verdelen.', 'negative_superfat_warning' => 'Een negatieve overvetting laat overtollige loog achter. Zonder correcte neutralisatie en tests kan het product irritatie of brandwonden veroorzaken. Doorgaan?'],
];
