<?php

return [
    'headings' => ['soap_qualities' => 'Soapkraft-eigenschappen', 'fatty_acid_profile' => 'Vetzuurprofiel'],
    'common' => ['ingredient' => 'Ingrediënt', 'oil' => 'Olie', 'weight' => 'Gewicht', 'additives' => 'Toevoegingen', 'fragrance' => 'Geur en aroma’s', 'fatty_acids' => 'Vetzuren', 'lye_type' => 'Soort loog', 'dual_lye' => 'Gemengde loog', 'superfat' => 'Overvetting', 'rinse_off' => 'Afspoelproduct', 'leave_on' => 'Niet-afspoelbaar product', 'product_category' => 'Productcategorie', 'choose_later' => 'Later kiezen', 'total_batch' => 'Totale batchhoeveelheid', 'cosmetic_categories_unavailable' => 'Productcategorieën zijn momenteel niet beschikbaar.', 'label_compliance' => 'Etiket en regelgeving', 'water_percent' => 'Water als % van de oliën', 'water_ratio' => 'Verhouding water : loog', 'lye_concentration' => 'Loogconcentratie', 'formula_percent' => '% van de formule'],
    'header' => ['section' => 'Product', 'product_name' => 'Productnaam', 'untitled_soap' => 'Naamloze zeep', 'untitled_cosmetic' => 'Naamloos cosmeticaproduct', 'product_sheet' => 'Productblad', 'locked' => 'Vergrendeld', 'saving' => 'Opslaan…', 'save' => 'Opslaan', 'lock_product' => 'Product vergrendelen', 'unlock_product' => 'Product ontgrendelen', 'more_actions' => 'Meer acties', 'product_details' => 'Productgegevens', 'duplicate_product' => 'Product dupliceren', 'new_product' => 'Nieuw product', 'current_product' => 'Huidig product', 'new_soap' => 'Nieuwe zeep', 'new_cosmetic' => 'Nieuw cosmeticaproduct'],
    'tabs' => ['aria_label' => 'Productonderdelen', 'formula' => 'Formule', 'packaging' => 'Verpakking', 'costing' => 'Kosten', 'output' => 'Etiket en uitvoer', 'instructions' => 'Instructies en media'],
    'settings' => ['title' => 'Formule-instellingen', 'hide' => 'Instellingen verbergen', 'edit' => 'Instellingen bewerken', 'total_oil_weight' => 'Totaalgewicht van de oliën', 'entry_mode' => 'Hoeveelheden invoeren als', 'water_mode' => 'Water berekenen op basis van', 'product_use' => 'Productgebruik', 'regulatory_framework' => 'Regelgevingskader', 'ifra_category' => 'IFRA-categorie', 'no_ifra_category' => 'Geen IFRA-categorie geselecteerd', 'ifra_unavailable' => 'IFRA-categorieën zijn momenteel niet beschikbaar.'],
    'ingredients' => ['title' => 'Ingrediënten toevoegen', 'search_placeholder' => 'Zoeken op naam of INCI', 'search_label' => 'Ingrediënten zoeken', 'count_singular' => '1 ingrediënt', 'count_plural' => ':count ingrediënten', 'properties' => 'Eigenschappen', 'ownership_note' => 'Door gebruikers gemaakte of gewijzigde ingrediënten zijn gemarkeerd met een punt. Soapkraft heeft de gegevens niet gecontroleerd.'],
    'saponification' => ['title' => 'Verzeping', 'balanced' => 'Oliën vormen 100%', 'unbalanced' => 'Oliën moeten samen 100% zijn', 'lye_water' => 'Loog en water', 'empty' => 'Voeg hier een olie toe of sleep deze hierheen', 'total_oils' => 'Totaal oliën', 'warning' => 'De oliën moeten samen 100% zijn voordat je opslaat.'],
    'additions' => ['title' => 'Formuletoevoegingen', 'additives_help' => 'Kleurstoffen, conserveermiddelen en andere functionele ingrediënten.', 'fragrance_help' => 'Parfumoliën, etherische oliën en aromatische extracten.', 'empty_oil' => 'Sleep hier een olie heen om deze als toevoeging te gebruiken.', 'batch_totals' => 'Batchtotalen'],
    'qualities' => ['disclaimer' => 'Deze waarden zijn schattingen. Het proces, de toevoegingen en de rijpingsomstandigheden beïnvloeden de uiteindelijke zeep.', 'review_title' => 'Aandachtspunten', 'empty' => 'Voeg oliën met SAP- en vetzuurgegevens toe om de zeepeigenschappen te berekenen.'],
    'fatty_acids' => ['details' => 'Afzonderlijke vetzuren', 'empty' => 'Voeg oliën met vetzuurgegevens toe om het mengprofiel te bekijken.'],
    'status' => ['title' => 'Formulestatus', 'oils' => 'Oliën', 'lye_water' => 'Loog en water', 'missing_quantities' => 'Ontbrekende hoeveelheden', 'changes' => 'Wijzigingen', 'ready' => 'Klaar om op te slaan.', 'amounts_calculated' => 'Hoeveelheden berekend.', 'waiting' => 'Voeg oliën toe en rond de instellingen af.', 'zero_detail' => 'Deze ingrediënten blijven in de formule staan totdat je hoeveelheden invult.', 'save_changes' => 'Sla op om deze wijzigingen te bewaren.', 'pending' => 'In afwachting', 'none' => 'Geen', 'saved' => 'Opgeslagen', 'unsaved' => 'Niet opgeslagen', 'saving' => 'Opslaan', 'save_failed' => 'Opslaan mislukt', 'saved_detail' => 'De huidige wijzigingen zijn opgeslagen.', 'saving_detail' => 'De huidige wijzigingen worden opgeslagen.', 'balanced_remaining' => 'Nog :amount% te verdelen.', 'negative_superfat_warning' => 'Een negatieve overvetting laat overtollige loog achter. Zonder correcte neutralisatie en tests kan het product irritatie of brandwonden veroorzaken. Doorgaan?'],
];
