<?php

return [
    'categories' => ['all' => 'Tutti', 'carrier_oil' => 'Oli vettori', 'essential_oil' => 'Oli essenziali', 'fragrance_oil' => 'Fragranze', 'botanical_extract' => 'Estratti botanici', 'co2_extract' => 'Estratti di CO2', 'liquid' => 'Liquidi', 'glycol' => 'Glicoli', 'clay' => 'Argille', 'colorant' => 'Coloranti', 'preservative' => 'Conservanti', 'additive' => 'Additivi'],
    'accessibility' => ['formula_save_bar' => 'Barra di salvataggio della formula', 'zero_quantity_note' => 'Gli ingredienti con quantità zero restano nella formula.', 'weight_unit' => 'Unità di peso', 'entry_mode' => 'Modalità di inserimento delle quantità', 'product_use' => 'Uso del prodotto', 'filter_category' => 'Filtra per categoria', 'ingredient_list' => 'Elenco degli ingredienti', 'user_owned' => 'Ingrediente creato o modificato dall’utente', 'show_ingredient_details' => 'Mostra i dettagli dell’ingrediente', 'ingredient_details' => 'Dettagli dell’ingrediente', 'add_ingredient' => 'Aggiungi ingrediente', 'choose_phase' => 'Scegli una fase per questo ingrediente'],
    'cosmetic' => ['title' => 'Ingredienti della formula', 'instruction' => 'Organizza gli ingredienti per fase, quindi inserisci una percentuale o un peso.', 'phase' => 'Fase', 'phase_name' => 'Nome della fase', 'move_up' => 'Sposta su', 'move_down' => 'Sposta giù', 'percent_of_formula' => ':percentage% della formula', 'remove_phase' => 'Rimuovi fase', 'drop_here' => 'Trascina qui gli ingredienti', 'formula_total' => 'Totale formula', 'add_phase' => 'Aggiungi fase', 'formula_balanced' => 'La formula totalizza il 100%', 'formula_unbalanced' => 'La formula deve totalizzare il 100%', 'balance_label' => 'Totale formula', 'blend_only' => 'Solo miscelazione', 'category_label' => 'Categoria', 'entry_label' => 'Quantità', 'exposure_label' => 'Uso del prodotto', 'label_label' => 'Etichetta', 'label_context' => 'Contesto dell’etichetta', 'quantity_complete_singular' => '1 ingrediente ha una quantità.', 'quantity_complete_plural' => ':count ingredienti hanno una quantità.', 'no_screening_rules' => 'Nessuna regola di controllo per questo quadro.', 'allergen_singular' => ':count allergene', 'allergen_plural' => ':count allergeni', 'substance_singular' => ':count sostanza', 'substance_plural' => ':count sostanze', 'show' => 'Mostra', 'hide' => 'Nascondi', 'show_details' => 'Mostra dettagli', 'hide_details' => 'Nascondi dettagli', 'weight_with_unit' => 'Peso (:unit)', 'add_to_phase' => 'Aggiungi a :phase', 'drag_ingredient' => 'Trascina per riordinare questo ingrediente', 'show_ingredient_details' => 'Mostra i dettagli dell’ingrediente', 'remove_ingredient' => 'Rimuovi ingrediente', 'percentage_for' => 'Percentuale di :ingredient', 'weight_for' => 'Peso di :ingredient'],
    'headings' => ['soap_qualities' => 'Qualità Soapkraft', 'fatty_acid_profile' => 'Profilo degli acidi grassi'],
    'common' => ['ingredient' => 'Ingrediente', 'oil' => 'Olio', 'weight' => 'Peso', 'additives' => 'Additivi', 'fragrance' => 'Fragranze e aromi', 'fatty_acids' => 'Acidi grassi', 'lye_type' => 'Tipo di alcali', 'dual_lye' => 'Alcali misto', 'superfat' => 'Superfat', 'rinse_off' => 'Da risciacquo', 'leave_on' => 'Senza risciacquo', 'product_category' => 'Categoria di prodotto', 'choose_later' => 'Scegli più tardi', 'total_batch' => 'Quantità totale del lotto', 'cosmetic_categories_unavailable' => 'Le categorie di prodotto non sono al momento disponibili.', 'label_compliance' => 'Etichetta e conformità', 'water_percent' => 'Acqua in % degli oli', 'water_ratio' => 'Rapporto acqua : alcali', 'lye_concentration' => 'Concentrazione dell’alcali', 'formula_percent' => '% della formula'],
    'header' => ['section' => 'Prodotto', 'product_name' => 'Nome del prodotto', 'untitled_soap' => 'Sapone senza titolo', 'untitled_cosmetic' => 'Prodotto cosmetico senza titolo', 'product_sheet' => 'Scheda prodotto', 'locked' => 'Bloccato', 'saving' => 'Salvataggio…', 'save' => 'Salva', 'lock_product' => 'Blocca prodotto', 'unlock_product' => 'Sblocca prodotto', 'more_actions' => 'Altre azioni', 'product_details' => 'Dettagli del prodotto', 'duplicate_product' => 'Duplica prodotto', 'new_product' => 'Nuovo prodotto', 'current_product' => 'Prodotto attuale', 'new_soap' => 'Nuovo sapone', 'new_cosmetic' => 'Nuovo prodotto cosmetico'],
    'tabs' => ['aria_label' => 'Sezioni del prodotto', 'formula' => 'Formula', 'packaging' => 'Confezionamento', 'costing' => 'Costi', 'output' => 'Etichetta e risultato', 'instructions' => 'Istruzioni e media'],
    'settings' => ['title' => 'Impostazioni della formula', 'hide' => 'Nascondi impostazioni', 'edit' => 'Modifica impostazioni', 'total_oil_weight' => 'Peso totale degli oli', 'entry_mode' => 'Inserisci le quantità in', 'water_mode' => 'Calcola l’acqua in base a', 'product_use' => 'Uso del prodotto', 'regulatory_framework' => 'Quadro normativo', 'ifra_category' => 'Categoria IFRA', 'no_ifra_category' => 'Nessuna categoria IFRA selezionata', 'ifra_unavailable' => 'Le categorie IFRA non sono al momento disponibili.'],
    'ingredients' => ['title' => 'Aggiungi ingredienti', 'search_placeholder' => 'Cerca per nome o INCI', 'search_label' => 'Cerca ingredienti', 'count_singular' => '1 ingrediente', 'count_plural' => ':count ingredienti', 'properties' => 'Proprietà', 'ownership_note' => 'Gli ingredienti creati o modificati dall’utente sono contrassegnati da un punto. Soapkraft non ne ha verificato i dati.'],
    'saponification' => ['title' => 'Saponificazione', 'balanced' => 'Oli al 100%', 'unbalanced' => 'Gli oli devono totalizzare il 100%', 'lye_water' => 'Alcali e acqua', 'empty' => 'Aggiungi o trascina qui un olio', 'total_oils' => 'Totale oli', 'warning' => 'Gli oli devono totalizzare il 100% prima del salvataggio.'],
    'additions' => ['title' => 'Aggiunte alla formula', 'additives_help' => 'Coloranti, conservanti e altri ingredienti funzionali.', 'fragrance_help' => 'Fragranze, oli essenziali ed estratti aromatici.', 'empty_oil' => 'Trascina qui un olio per usarlo come aggiunta.', 'batch_totals' => 'Totali del lotto'],
    'qualities' => ['disclaimer' => 'Questi valori sono stime. Il processo, le aggiunte e le condizioni di stagionatura influenzano il sapone finito.', 'review_title' => 'Punti da verificare', 'empty' => 'Aggiungi oli con dati SAP e sugli acidi grassi per calcolare le qualità del sapone.'],
    'fatty_acids' => ['details' => 'Singoli acidi grassi', 'empty' => 'Aggiungi oli con dati sugli acidi grassi per vedere il profilo della miscela.'],
    'status' => ['title' => 'Stato della formula', 'oils' => 'Oli', 'lye_water' => 'Alcali e acqua', 'missing_quantities' => 'Quantità mancanti', 'changes' => 'Modifiche', 'ready' => 'Pronto per il salvataggio.', 'amounts_calculated' => 'Quantità calcolate.', 'waiting' => 'Aggiungi gli oli e completa le impostazioni.', 'zero_detail' => 'Questi ingredienti restano nella formula finché non inserisci le quantità.', 'save_changes' => 'Salva per conservare queste modifiche.', 'pending' => 'In attesa', 'none' => 'Nessuna', 'saved' => 'Salvato', 'unsaved' => 'Non salvato', 'saving' => 'Salvataggio', 'save_failed' => 'Salvataggio non riuscito', 'saved_detail' => 'Le modifiche attuali sono state salvate.', 'saving_detail' => 'Salvataggio delle modifiche in corso.', 'balanced_remaining' => 'Resta da bilanciare il :amount%.', 'negative_superfat_warning' => 'Un superfat negativo lascia alcali in eccesso. Se il prodotto non viene neutralizzato e testato correttamente, può causare irritazioni o ustioni. Continuare?'],
];
