<?php

return [
    'headings' => ['soap_qualities' => 'Cualidades Soapkraft', 'fatty_acid_profile' => 'Perfil de ácidos grasos'],
    'common' => ['ingredient' => 'Ingrediente', 'oil' => 'Aceite', 'weight' => 'Peso', 'additives' => 'Aditivos', 'fragrance' => 'Fragancias y aromas', 'fatty_acids' => 'Ácidos grasos', 'lye_type' => 'Tipo de álcali', 'dual_lye' => 'Álcali mixto', 'superfat' => 'Sobreengrasado', 'rinse_off' => 'Con aclarado', 'leave_on' => 'Sin aclarado', 'product_category' => 'Categoría de producto', 'choose_later' => 'Elegir más tarde', 'total_batch' => 'Cantidad total del lote', 'cosmetic_categories_unavailable' => 'Las categorías de producto no están disponibles en este momento.', 'label_compliance' => 'Etiqueta y cumplimiento', 'water_percent' => 'Agua como % de los aceites', 'water_ratio' => 'Proporción agua : álcali', 'lye_concentration' => 'Concentración de álcali', 'formula_percent' => '% de la fórmula'],
    'header' => ['section' => 'Producto', 'product_name' => 'Nombre del producto', 'untitled_soap' => 'Jabón sin título', 'untitled_cosmetic' => 'Producto cosmético sin título', 'product_sheet' => 'Ficha del producto', 'locked' => 'Bloqueado', 'saving' => 'Guardando…', 'save' => 'Guardar', 'lock_product' => 'Bloquear producto', 'unlock_product' => 'Desbloquear producto', 'more_actions' => 'Más acciones', 'product_details' => 'Detalles del producto', 'duplicate_product' => 'Duplicar producto', 'new_product' => 'Producto nuevo', 'current_product' => 'Producto actual', 'new_soap' => 'Jabón nuevo', 'new_cosmetic' => 'Producto cosmético nuevo'],
    'tabs' => ['aria_label' => 'Secciones del producto', 'formula' => 'Fórmula', 'packaging' => 'Envasado', 'costing' => 'Costes', 'output' => 'Etiqueta y resultado', 'instructions' => 'Instrucciones y archivos'],
    'settings' => ['title' => 'Ajustes de la fórmula', 'hide' => 'Ocultar ajustes', 'edit' => 'Editar ajustes', 'total_oil_weight' => 'Peso total de los aceites', 'entry_mode' => 'Introducir cantidades en', 'water_mode' => 'Calcular el agua según', 'product_use' => 'Uso del producto', 'regulatory_framework' => 'Marco normativo', 'ifra_category' => 'Categoría IFRA', 'no_ifra_category' => 'Ninguna categoría IFRA seleccionada', 'ifra_unavailable' => 'Las categorías IFRA no están disponibles en este momento.'],
    'ingredients' => ['title' => 'Añadir ingredientes', 'search_placeholder' => 'Buscar por nombre o INCI', 'search_label' => 'Buscar ingredientes', 'count_singular' => '1 ingrediente', 'count_plural' => ':count ingredientes', 'properties' => 'Propiedades', 'ownership_note' => 'Los ingredientes creados o modificados por el usuario se indican con un punto. Soapkraft no ha verificado sus datos.'],
    'saponification' => ['title' => 'Saponificación', 'balanced' => 'Aceites al 100 %', 'unbalanced' => 'Los aceites deben sumar el 100 %', 'lye_water' => 'Álcali y agua', 'empty' => 'Añade o suelta un aceite aquí', 'total_oils' => 'Total de aceites', 'warning' => 'Los aceites deben sumar el 100 % antes de guardar.'],
    'additions' => ['title' => 'Adiciones a la fórmula', 'additives_help' => 'Colorantes, conservantes y otros ingredientes funcionales.', 'fragrance_help' => 'Fragancias, aceites esenciales y extractos aromáticos.', 'empty_oil' => 'Suelta aquí un aceite para usarlo como adición.', 'batch_totals' => 'Totales del lote'],
    'qualities' => ['disclaimer' => 'Estos valores son estimaciones. El proceso, las adiciones y las condiciones de curado influyen en el jabón final.', 'review_title' => 'Puntos que revisar', 'empty' => 'Añade aceites con datos de SAP y ácidos grasos para calcular las cualidades del jabón.'],
    'fatty_acids' => ['details' => 'Ácidos grasos individuales', 'empty' => 'Añade aceites con datos de ácidos grasos para ver el perfil de la mezcla.'],
    'status' => ['title' => 'Estado de la fórmula', 'oils' => 'Aceites', 'lye_water' => 'Álcali y agua', 'missing_quantities' => 'Cantidades pendientes', 'changes' => 'Cambios', 'ready' => 'Listo para guardar.', 'amounts_calculated' => 'Cantidades calculadas.', 'waiting' => 'Añade aceites y completa los ajustes.', 'zero_detail' => 'Estos ingredientes permanecerán en la fórmula hasta que indiques sus cantidades.', 'save_changes' => 'Guarda para conservar estos cambios.', 'pending' => 'Pendiente', 'none' => 'Ninguna', 'saved' => 'Guardado', 'unsaved' => 'Sin guardar', 'saving' => 'Guardando', 'save_failed' => 'No se ha podido guardar', 'saved_detail' => 'Los cambios actuales están guardados.', 'saving_detail' => 'Guardando los cambios actuales.', 'balanced_remaining' => 'Falta equilibrar un :amount %.', 'negative_superfat_warning' => 'Un sobreengrasado negativo deja un exceso de álcali. Si el producto no se neutraliza y comprueba correctamente, puede causar irritación o quemaduras. ¿Continuar?'],
];
