<?php

return [
    'enabled' => env('CONTEXTUAL_HELP_ENABLED', true),
    'disk' => env('CONTEXTUAL_HELP_DISK', 'r2_backups'),
    'queue' => 'content',
    'translation' => [
        'model' => env('HELP_TRANSLATION_MODEL'),
        'reasoning_effort' => env('HELP_TRANSLATION_REASONING_EFFORT'),
        'prompt_version' => 'help-translation-v1',
    ],
    'topics' => [
        'shared.formula_basics' => ['domain' => 'shared_workbench'],
        'shared.ingredient_selection' => ['domain' => 'shared_workbench'],
        'shared.quantities_and_units' => ['domain' => 'shared_workbench'],
        'shared.saving_and_history' => ['domain' => 'shared_workbench'],
        'shared.formula_lock' => ['domain' => 'shared_workbench'],
        'shared.packaging' => ['domain' => 'shared_workbench'],
        'shared.costing' => ['domain' => 'shared_workbench'],
        'shared.manufacturing_procedure' => ['domain' => 'shared_workbench'],
        'shared.media' => ['domain' => 'shared_workbench'],
        'shared.compliance_guidance' => ['domain' => 'shared_workbench'],
        'shared.ingredient_change_review' => ['domain' => 'shared_workbench'],
        'soap.reaction_core' => ['domain' => 'soap_workbench'],
        'soap.alkali_and_purity' => ['domain' => 'soap_workbench'],
        'soap.water_mode' => ['domain' => 'soap_workbench'],
        'soap.dilution_liquids' => ['domain' => 'soap_workbench'],
        'soap.superfat' => ['domain' => 'soap_workbench'],
        'soap.post_reaction_additions' => ['domain' => 'soap_workbench'],
        'soap.fatty_acids' => ['domain' => 'soap_workbench'],
        'soap.qualities' => ['domain' => 'soap_workbench'],
        'soap.qualities.cure' => ['domain' => 'soap_workbench'],
        'soap.qualities.dos' => ['domain' => 'soap_workbench'],
        'soap.qualities.liquid' => ['domain' => 'soap_workbench'],
        'soap.output_basis' => ['domain' => 'soap_workbench'],
        'soap.labeling' => ['domain' => 'soap_workbench'],
        'cosmetic.formula_basis' => ['domain' => 'cosmetic_workbench'],
        'cosmetic.phases' => ['domain' => 'cosmetic_workbench'],
        'cosmetic.ingredient_functions' => ['domain' => 'cosmetic_workbench'],
        'cosmetic.application_context' => ['domain' => 'cosmetic_workbench'],
        'cosmetic.preservation_and_ph' => ['domain' => 'cosmetic_workbench'],
        'cosmetic.output_basis' => ['domain' => 'cosmetic_workbench'],
        'cosmetic.labeling' => ['domain' => 'cosmetic_workbench'],
        'shared.ifra_context' => ['domain' => 'shared_workbench'],
    ],
];
