<?php

return [
    'enabled' => env('CONTEXTUAL_HELP_ENABLED', true),
    'disk' => env('CONTEXTUAL_HELP_DISK', 'r2_backups'),
    'queue' => env('INGREDIENT_ENRICHMENT_QUEUE', 'enrichment'),
    'translation' => [
        'model' => env('HELP_TRANSLATION_MODEL'),
        'reasoning_effort' => env('HELP_TRANSLATION_REASONING_EFFORT'),
        'prompt_version' => 'help-translation-v1',
    ],
    'topics' => [
        'products.getting_started' => ['domain' => 'application'],
        'products.finding_and_archiving' => ['domain' => 'application'],
        'products.versions_and_copies' => ['domain' => 'application'],
        'media.uploading' => ['domain' => 'application'],
        'media.organizing' => ['domain' => 'application'],
        'media.reuse_and_removal' => ['domain' => 'application'],
        'settings.language' => ['domain' => 'application'],
        'settings.numbers' => ['domain' => 'application'],
        'settings.workspace' => ['domain' => 'application'],

        'ingredients.catalogue' => ['domain' => 'material_library'],
        'ingredients.duplicate' => ['domain' => 'material_library'],
        'ingredients.identity' => ['domain' => 'material_library'],
        'ingredients.classification' => ['domain' => 'material_library'],
        'ingredients.composition' => ['domain' => 'material_library'],
        'ingredients.soap_chemistry' => ['domain' => 'material_library'],
        'ingredients.guidance_and_documents' => ['domain' => 'material_library'],
        'ingredients.editing_and_removal' => ['domain' => 'material_library'],
        'materials.codes' => ['domain' => 'material_library'],
        'materials.prices' => ['domain' => 'material_library'],
        'packaging.library' => ['domain' => 'material_library'],
        'packaging.quantities_and_costs' => ['domain' => 'material_library'],
        'packaging.editing_and_removal' => ['domain' => 'material_library'],

        'production.planning' => ['domain' => 'production_runs'],
        'production.formula_snapshot' => ['domain' => 'production_runs'],
        'production.batch_size' => ['domain' => 'production_runs'],
        'production.scheduling' => ['domain' => 'production_runs'],
        'production.flash_planning' => ['domain' => 'production_runs'],
        'production.stock_preparation' => ['domain' => 'production_runs'],
        'production.start_and_actuals' => ['domain' => 'production_runs'],
        'production.completion' => ['domain' => 'production_runs'],
        'production.output_lot' => ['domain' => 'production_runs'],
        'production.tasks' => ['domain' => 'production_runs'],
        'production.task_sets' => ['domain' => 'production_runs'],
        'production.journal' => ['domain' => 'production_runs'],
        'production.cancel_abort' => ['domain' => 'production_runs'],

        'purchasing.suppliers' => ['domain' => 'production_purchasing'],
        'purchasing.listings' => ['domain' => 'production_purchasing'],
        'purchasing.purchase_formats' => ['domain' => 'production_purchasing'],
        'purchasing.prices_and_currency' => ['domain' => 'production_purchasing'],
        'purchasing.quotations' => ['domain' => 'production_purchasing'],
        'purchasing.purchase_orders' => ['domain' => 'production_purchasing'],
        'purchasing.incoming_stock' => ['domain' => 'production_purchasing'],
        'purchasing.receiving_deliveries' => ['domain' => 'production_purchasing'],
        'purchasing.partial_deliveries' => ['domain' => 'production_purchasing'],
        'purchasing.corrections' => ['domain' => 'production_purchasing'],
        'purchasing.receipt_documents' => ['domain' => 'production_purchasing'],

        'inventory.overview' => ['domain' => 'production_inventory'],
        'inventory.quantities' => ['domain' => 'production_inventory'],
        'inventory.lots_and_status' => ['domain' => 'production_inventory'],
        'inventory.opening_stock' => ['domain' => 'production_inventory'],
        'inventory.receiving_stock' => ['domain' => 'production_inventory'],
        'inventory.adjustments' => ['domain' => 'production_inventory'],
        'inventory.reservations' => ['domain' => 'production_inventory'],
        'inventory.buffer_stock' => ['domain' => 'production_inventory'],
        'inventory.storage_locations' => ['domain' => 'production_inventory'],
        'inventory.material_history' => ['domain' => 'production_inventory'],

        'shared.formula_basics' => ['domain' => 'shared_workbench'],
        'shared.ingredient_selection' => ['domain' => 'shared_workbench'],
        'shared.quantities_and_units' => ['domain' => 'shared_workbench'],
        'shared.saving_and_history' => ['domain' => 'shared_workbench'],
        'shared.formula_lock' => ['domain' => 'shared_workbench'],
        'shared.packaging' => ['domain' => 'shared_workbench'],
        'shared.costing' => ['domain' => 'shared_workbench'],
        'shared.manufacturing_procedure' => ['domain' => 'shared_workbench'],
        'shared.media' => ['domain' => 'shared_workbench'],
        'shared.compliance_guidance' => ['domain' => 'shared_workbench'],
        'shared.ingredient_change_review' => ['domain' => 'shared_workbench'],
        'soap.reaction_core' => ['domain' => 'soap_workbench'],
        'soap.alkali_and_purity' => ['domain' => 'soap_workbench'],
        'soap.water_mode' => ['domain' => 'soap_workbench'],
        'soap.dilution_liquids' => ['domain' => 'soap_workbench'],
        'soap.superfat' => ['domain' => 'soap_workbench'],
        'soap.post_reaction_additions' => ['domain' => 'soap_workbench'],
        'soap.fatty_acids' => ['domain' => 'soap_workbench'],
        'soap.qualities' => ['domain' => 'soap_workbench'],
        'soap.qualities.cure' => ['domain' => 'soap_workbench'],
        'soap.qualities.dos' => ['domain' => 'soap_workbench'],
        'soap.qualities.liquid' => ['domain' => 'soap_workbench'],
        'soap.output_basis' => ['domain' => 'soap_workbench'],
        'soap.labeling' => ['domain' => 'soap_workbench'],
        'cosmetic.formula_basis' => ['domain' => 'cosmetic_workbench'],
        'cosmetic.phases' => ['domain' => 'cosmetic_workbench'],
        'cosmetic.ingredient_functions' => ['domain' => 'cosmetic_workbench'],
        'cosmetic.application_context' => ['domain' => 'cosmetic_workbench'],
        'cosmetic.preservation_and_ph' => ['domain' => 'cosmetic_workbench'],
        'cosmetic.output_basis' => ['domain' => 'cosmetic_workbench'],
        'cosmetic.labeling' => ['domain' => 'cosmetic_workbench'],
        'shared.ifra_context' => ['domain' => 'shared_workbench'],
    ],
];
