<?php

return [
    'input_format' => 'soapkraft-platform-ingredient-enrichment-input',
    'result_format' => 'soapkraft-platform-ingredient-enrichment-result',
    'schema_version' => 4,
    'default_export_path' => 'storage/app/private/ingredient-enrichment/platform-ingredients.jsonl',
    'batch_artifacts' => [
        'disk' => env('INGREDIENT_ENRICHMENT_ARTIFACT_DISK', 'local'),
        'directory' => 'ingredient-enrichment/batches',
    ],
    'intake' => [
        'maximum_batch_size' => (int) env('INGREDIENT_INTAKE_MAXIMUM_BATCH_SIZE', 100),
        'artifacts' => [
            'disk' => env('INGREDIENT_INTAKE_ARTIFACT_DISK', 'local'),
            'directory' => env('INGREDIENT_INTAKE_ARTIFACT_DIRECTORY', 'ingredient-intake'),
        ],
    ],
    'market_codes' => ['eu', 'us'],
    'source_hosts_by_tier' => [
        'official' => [
            'api.fda.gov',
            'ec.europa.eu',
            'ecfr.gov',
            'eur-lex.europa.eu',
            'fda.gov',
            'gsrs.ncats.nih.gov',
            'precision.fda.gov',
            'single-market-economy.ec.europa.eu',
        ],
        'structured_mirror' => ['cosingchecker.com'],
        'editorial' => [
            'ec.europa.eu',
            'single-market-economy.ec.europa.eu',
            'eur-lex.europa.eu',
            'echa.europa.eu',
            'commonchemistry.cas.org',
            'pubchem.ncbi.nlm.nih.gov',
            'powo.science.kew.org',
            'fda.gov',
            'ecfr.gov',
            'pubmed.ncbi.nlm.nih.gov',
            'cir-safety.org',
            'cosmileeurope.eu',
        ],
    ],
    'guidance' => [
        'minimum_words' => 0,
        'maximum_words' => 240,
        'maximum_characters' => 2000,
        'required_headings' => ['Overview', 'Formulation use'],
        'soapmaking_heading' => 'Soapmaking',
        'localized_headings' => [
            'de' => ['overview' => 'Überblick', 'formulation_use' => 'Verwendung in Formulierungen', 'soapmaking' => 'Seifenherstellung'],
            'es' => ['overview' => 'Descripción general', 'formulation_use' => 'Uso en formulación', 'soapmaking' => 'Elaboración de jabón'],
            'fr' => ['overview' => 'Vue d’ensemble', 'formulation_use' => 'Utilisation en formulation', 'soapmaking' => 'Savonnerie'],
            'it' => ['overview' => 'Panoramica', 'formulation_use' => 'Uso in formulazione', 'soapmaking' => 'Saponificazione'],
            'nl' => ['overview' => 'Overzicht', 'formulation_use' => 'Gebruik in formuleringen', 'soapmaking' => 'Zeepmaken'],
            'pt_BR' => ['overview' => 'Visão geral', 'formulation_use' => 'Uso na formulação', 'soapmaking' => 'Saboaria'],
        ],
    ],
    'direct_ai' => [
        'enabled' => env('INGREDIENT_ENRICHMENT_AI_ENABLED', false),
        'queue' => env('INGREDIENT_ENRICHMENT_QUEUE', 'enrichment'),
        'default_batch_size' => (int) env('INGREDIENT_ENRICHMENT_DEFAULT_BATCH_SIZE', 10),
        'maximum_batch_size' => (int) env('INGREDIENT_ENRICHMENT_MAXIMUM_BATCH_SIZE', 25),
        'job_timeout_seconds' => (int) env('INGREDIENT_ENRICHMENT_JOB_TIMEOUT', 2000),
    ],
    'source_transport' => [
        'connect_timeout_seconds' => (int) env('INGREDIENT_SOURCE_CONNECT_TIMEOUT', 5),
        'timeout_seconds' => (int) env('INGREDIENT_SOURCE_TIMEOUT', 20),
        'response_shape_version' => 'v1',
    ],
    'sources' => [
        'cosing_checker' => [
            'base_url' => env('COSING_CHECKER_BASE_URL', 'https://cosingchecker.com/api/v1'),
            'inventory_version' => '2026-03-21',
            'ttl_days' => 30,
        ],
        'eur_lex_glossary' => [
            'url' => 'https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32025D1175',
            'celex' => '32025D1175',
            'ttl_days' => 30,
        ],
        'open_fda' => [
            'base_url' => env('OPENFDA_BASE_URL', 'https://api.fda.gov/other/substance.json'),
            'source_version' => 'openfda-gsrs-v1',
            'ttl_days' => 30,
        ],
        'fda_colours' => [
            'url' => 'https://www.fda.gov/cosmetics/cosmetic-ingredient-names/color-additives-permitted-use-cosmetics',
            'ttl_days' => 7,
        ],
    ],
    'openai' => [
        'api_key' => env('OPENAI_API_KEY'),
        'base_url' => env('OPENAI_BASE_URL', 'https://api.openai.com/v1'),
        'model' => env('INGREDIENT_ENRICHMENT_MODEL', 'gpt-5.6-terra'),
        'reasoning_effort' => env('INGREDIENT_ENRICHMENT_REASONING_EFFORT', 'low'),
        'localization_model' => env('INGREDIENT_ENRICHMENT_LOCALIZATION_MODEL', 'gpt-5.6-luna'),
        'localization_reasoning_effort' => env('INGREDIENT_ENRICHMENT_LOCALIZATION_REASONING_EFFORT', 'xhigh'),
        'timeout_seconds' => (int) env('INGREDIENT_ENRICHMENT_TIMEOUT', 600),
        'connect_timeout_seconds' => (int) env('INGREDIENT_ENRICHMENT_CONNECT_TIMEOUT', 15),
        'prompt_version' => 'ingredient-enrichment-research-v3',
        'editorial_prompt_version' => 'ingredient-enrichment-metadata-v1',
        'guidance_prompt_version' => 'ingredient-guidance-v14',
        'guidance_localization_prompt_version' => 'ingredient-guidance-localization-v4',
        'identity_name_localization_prompt_version' => 'ingredient-identity-name-localization-v1',
        'allowed_domains' => [
            'ec.europa.eu',
            'single-market-economy.ec.europa.eu',
            'eur-lex.europa.eu',
            'echa.europa.eu',
            'commonchemistry.cas.org',
            'pubchem.ncbi.nlm.nih.gov',
            'powo.science.kew.org',
            'fda.gov',
            'ecfr.gov',
            'pubmed.ncbi.nlm.nih.gov',
            'cir-safety.org',
        ],
        'gap_research' => [
            'enabled' => env('INGREDIENT_ENRICHMENT_GAP_RESEARCH_ENABLED', false),
        ],
        'guidance_research' => [
            'enabled' => env('INGREDIENT_ENRICHMENT_GUIDANCE_RESEARCH_ENABLED', true),
            'prompt_version' => 'ingredient-guidance-research-v7',
            'maximum_tool_calls' => (int) env('INGREDIENT_ENRICHMENT_GUIDANCE_MAX_TOOL_CALLS', 5),
            'blocked_domains' => [
                'amazon.com',
                'ebay.com',
                'etsy.com',
                'aliexpress.com',
                'facebook.com',
                'instagram.com',
                'pinterest.com',
                'patents.google.com',
                'patentscope.wipo.int',
                'reddit.com',
                'tiktok.com',
                'youtube.com',
                'wikipedia.org',
                'worldwide.espacenet.com',
            ],
            'allowed_claim_types' => [
                'origin',
                'physical_form',
                'formulation_role',
                'processing',
                'dispersion',
                'solubility',
                'compatibility',
                'sensory',
                'stability',
                'usage',
                'soapmaking',
            ],
            'allowed_source_kinds' => [
                'manufacturer_technical',
                'supplier_technical',
                'scientific',
                'regulatory_reference',
                'professional_reference',
                'specialist_reference',
            ],
            'allowed_scopes' => ['material', 'product_grade'],
            'allowed_evidence_kinds' => [
                'fact',
                'formulation_recommendation',
                'experimental_observation',
            ],
            'allowed_usage_applications' => ['cosmetics', 'soapmaking', 'not_applicable'],
            'allowed_percentage_bases' => ['total_formula', 'oil_phase', 'soap_oils', 'not_applicable'],
        ],
    ],
];
